# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-06 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u673a\u6784\u6807\u7b7e'),
        ),
    ]
