# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-16 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '\u5b66\u4e60\u7684\u8bfe\u7a0b', 'verbose_name_plural': '\u5b66\u4e60\u7684\u8bfe\u7a0b'},
        ),
    ]
