# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_is_banner'),
        ('operation', '0004_auto_20181107_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='\u6570\u636eid'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '\u8bfe\u7a0b'), (2, '\u8bfe\u7a0b\u673a\u6784'), (3, '\u8bb2\u5e08')], default=1, verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='comments',
            field=models.CharField(default='', max_length=200, verbose_name='\u8bc4\u8bba'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='course',
            field=models.ManyToManyField(to='courses.Course', verbose_name='\u8bfe\u7a0b'),
        ),
    ]
