# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-07 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20181107_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='fav_id',
        ),
        migrations.RemoveField(
            model_name='coursecomments',
            name='fav_type',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='comments',
        ),
    ]
