# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='\u7ae0\u8282\u65f6\u957f(\u5206\u949f\u6570)'),
        ),
    ]
